spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/reportes
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Mantener la conexión activa si está inactiva mucho tiempo
spring.datasource.validationQuery=SELECT 1

# Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Server
server.port=8080
server.error.whitelabel.enabled=false

profile=dev

# Configuración de JasperReports
spring.jasperreports.enabled=true
spring.jasperreports.view-names=report_*
spring.jasperreports.cache=false
